config/routes.rb
Rails.application.routes.draw do

  root              'static_pages#home'

  get  'help',  to: 'static_pages#help'

  get  'about', to: 'static_pages#about'

  devise_for :users

  post 'print', defaults: { format: 'pdf' }, to: 'users#print'

  resources :pdf_templates

  resources :organizations do
    resources :members
    member { post 'print', defaults: { format: 'pdf' } }
  end

  resources :members, only: [:index]

  resources :groups do
    resources :members, only: [:index], controller: 'groups/members' do
      member do
        get 'add'
        get 'remove'
      end
    end
    resources :events do
      member { post 'print', defaults: { format: 'pdf' } }
    end
    member { post 'print', defaults: { format: 'pdf' } }
  end

  resources :events do
    resources :registrations, 
              only: [:index, :destroy], 
              controller: 'events/registrations' do
      member { get 'confirm' } 
    end

    member { get 'register', to: 'events/registrations#register' }
  end

  get "angular_test", to: "angular_test#index"

end

app/models/group.rb
class Group < ActiveRecord::Base
  include PdfTemplate::Printer

  belongs_to :user
  has_many :events
  has_and_belongs_to_many :members

  validates :name, presence: true

  validates :website, format: { with: ApplicationHelper::WEBSITE_PATTERN,
                                message: "URI is not valid" }, 
                      allow_blank: true

  validates :email, format: { with: ApplicationHelper::EMAIL_PATTERN, 
                              message: "is not valid" }, allow_blank: true

  scope :by_name, -> { order(:name) }
end

app/models/group/search.rb
class Group::Search
  
  QUERY = "lower(name) like :name or " +
          "lower(website) like :website or " +
          "lower(description) like :description"

  attr_reader :result

  def initialize(groups, search_term)
    build_query_params(search_term.downcase)
    @result = groups.where(QUERY, @args).order(@order)
  end

  private

    def build_query_params(search_term)
      search_term =~ /[:\.\/]/ ? website_params(search_term) 
                               : name_params(search_term)
      build_order(search_term)
    end

    def name_params(search_term)
      @args = { name: begins_with(search_term), 
                description: contains(search_term), 
                website: contains(search_term) }

    end

    def website_params(search_term)
      # This regex would extract the website name without http://www. and .com
      # (?<=\/www|\/www\.)\w+|(?<=\/)\w+(?=\.\w+$)|\w+(?=\.\w+$|\.$)

      # This regex removes everything except the website name
      # ^.*\/+|.*www\.|\..*$
      name_term = search_term.gsub(/^.*\/+|.*www\.|\..*$/, "")

      @args = { name: begins_with(name_term), 
                description: contains(name_term), 
                website: begins_with(search_term) }
    end

    def build_order(search_term)
      @order = "website like " + 
               ActiveRecord::Base.connection.quote(search_term) +
               "desc, name asc"
    end

    def begins_with(search_term)
      search_term + "%"
    end

    def contains(search_term)
      "%" + search_term + "%"
    end

end

app/controllers/groups/members_controller.rb
class Groups::MembersController < ApplicationController

  before_action :load_user_and_group

  def index
    load_group_members
    load_non_group_members
  end

  def add
    load_member
    add_member_to_group
    redirect_to group_members_path @group
  end

  def remove
    load_member
    remove_member_from_group
    redirect_to group_members_path @group
  end

  private

    def load_user_and_group
      @user ||= current_user
      @group ||= user_groups.find(params[:group_id])
    end

    def load_group_members
      @group_members ||= group_members
    end

    def load_non_group_members
      @non_group_members ||= non_group_members
    end

    def load_member
      @member ||= all_members.find(params[:id])
    end

    def add_member_to_group
      @group.members << @member
    end

    def remove_member_from_group
      @group.members.delete(@group.members.find(@member.id))
    end

    def save_member
      @member.save
    end

    def user_groups
      @user.groups
    end

    def group_members
      if params[:group_member_search].present?
        Member::Search.new(@group.members, params[:group_member_search]).result
      else
        @group.members.joins(:organization)
              .order("organizations.name, members.first_name")
      end
    end

    def non_group_members
      member_selection = @user.members.where.not(id: @group.members) 
      if params[:member_search].present?
        Member::Search.new(member_selection, params[:member_search]).result
      else
        member_selection 
      end
    end

    def all_members
      @user.members 
    end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_action :load_user

  def index
    load_groups
  end

  def show
    load_group
    load_members
  end

  def new
    build_group
  end

  def create
    build_group
    save_group or render :new
  end

  def edit
    load_group
    build_group
  end

  def update
    load_group
    build_group
    save_group or render :edit
  end

  def destroy
    load_group
    @group.destroy
    redirect_to groups_path
  end

  def print
    load_group
    respond_to do |format|
      format.pdf do
        send_data @group.to_pdf(params[:template]),
          content_type: Mime::PDF
      end
    end
  end

  private

    def load_user
      @user = current_user
    end

    def load_groups
      @groups ||= user_groups
    end

    def load_group
      @group ||= user_groups.find(params[:id])
    end

    def load_members
      if params[:member_search].present?
        @members ||= Member::Search.new(@group.members, 
                                        params[:member_search]).result
      else
        @members ||= @group.members.joins(:organization)
                           .order("organizations.name, members.first_name")
      end
    end

    def build_group
      @group ||= user_groups.build
      @group.attributes = group_params
    end

    def save_group
      if @group.save
        redirect_to groups_path
      end
    end

    def group_params
      group_params = params[:group]
      group_params ? group_params.permit(:name, :description, :phone, 
                                         :email, :website) : {}
    end

    def user_groups
      if params[:keywords].present?
        Group::Search.new(@user.groups, params[:keywords]).result
      else
        @user.groups.by_name
      end
    end
end

app/helpers/groups/members_helper.rb
module Groups::MembersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for @group do |f| %>
  <%= render partial: 'shared/generic_error_message', 
    locals: { topic: @group } %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :phone %>
    <%= f.text_field :phone, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :website %>
    <%= f.text_field :website, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <%= f.submit class: "btn btn-primary" %> | <%= link_to "Cancel", :back %>
<% end %>

app/views/groups/edit.html.erb
<% provide(:title, "Edit #{@group.name}") %>

<h1>Edit group <%= @group.name %></h1>

<%= render 'form' %>

app/views/groups/index.html.erb
<% provide(:title, "Groups") %>

<header>
  <h1 class="h2">Group Search</h1>
</header>

<section class="search-form">
  <%= form_for :groups, method: :get do |f| %>
    <div class="input-group input-group-lg">
      <%= label_tag :keywords, nil, class: "sr-only" %>
      <%= text_field_tag :keywords, nil,
        placeholder: "Name, Website and Description", autofocus: true,
        class: "form-control input-lg" %>
      <span class="input-group-btn">
        <%= submit_tag "Find Groups", class: "btn btn-primary btn-lg" %>
      </span>
    </div>
  <% end %>
</section>

<section class="link-area">
  <br>
  <%= link_to "Create new group", new_group_path, 
    class: "btn btn-primary" %>
</section>

<section class="search-results">
  <header>
    <h1 class="h3">Results</h1>
  </header>
  <ol class="list-group">
    <% @groups.each do |group| %>
      <li class="list-group-item clearfix">
        <h2 class="pull-right">
          <%= link_to "View events...", group_events_path(group),
            class: "btn btn-default btn-sm" %>
          <%= link_to "View members...", group,
            class: "btn btn-default btn-sm" %>
          <%= link_to "Edit", 
            edit_group_path(group), 
            class: "btn btn-primary btn-sm" %> 
          <%= link_to "Delete", 
            group, 
            method: :delete, 
            data: { confirm: "You are about to delete #{group.name}. 
                    Do you want to delete now?" }, 
            class: "btn btn-warning btn-sm" %>
        </h2>
        <h2 class="h3">
          <i class="glyphicon glyphicon-flag"></i>
          <%= group.name %>
        </h2>
        <address>
          <%= if_phone group.phone %>
          <%= if_email group.email %>
          <%= if_website group.website, false %>
        </address>
        <%= if_blockquote group.description, group.name %>
        <%= render 'pdf_templates/printer', 
          klass: "Group", 
          path: print_group_path(group, params[:template]) %>
      </li>
    <% end %>
  </ol>
</section>

app/views/groups/new.html.erb
<% provide(:title, 'New Group') %>

<h1>Create new Group</h1>

<%= render 'form' %>

app/views/groups/show.html.erb
<% provide(:title, @group.name) %>

<div class="row">
  <div class="col-md-4">
    <article class="panel panel-default">
      <header class="panel-heading">
        <h2 class="h3">
          <i class="glyphicon glyphicon-flag"></i>
          <%= @group.name %>
        </h2>
      </header>
      <section class="panel-body">
        <address>
          <%= if_phone @group.phone %>
          <%= if_email @group.email %>
          <%= if_website @group.website, false %>
        </address>
        <%= if_blockquote @group.description, @group.name %>
      </section>
      <section class="panel-footer">
        <%= link_to "Back to groups", groups_path %>
      </section>
    </article>
  </div>
  <div class="col-md-8">
    <header>
      <h1 class="h2">Member Search</h1>
    </header>

    <section class="search-form">
      <%= form_for :groups, method: :get do |f| %>
        <div class="input-group input-group-lg">
          <%= label_tag :member_search, nil, class: "sr-only" %>
          <%= text_field_tag :member_search, nil,
            placeholder: "First Name, Name and Email", autofocus: true, 
            class: "form-control input-lg" %>
          <span class="input-group-btn">
            <%= submit_tag "Find Members", 
              class: "btn btn-primary btn-lg" %>
          </span>
        </div>
      <% end %>
    </section>

    <section class="link-area">
      <br>
      <%= mail_to distribution_list(@members), "Mail to group members",
        class: "btn btn-default pull-right" %>
      <%= link_to "Add new member", 
        group_members_path(@group), 
        class: "btn btn-primary" %>
    </section>  

    <section class="search-results">
      <header>
        <h1 class="h3">Results</h1>
      </header>
      <ol class="list-group">
        <% @members.each do |member| %>
          <li class="list-group-item clearfix">
            <h2 class="pull-right">
              <%= link_to "Edit", 
                edit_organization_member_path(member.organization, member), 
                class: "btn btn-primary btn-sm" %> 
            </h2>
            <%= render 'shared/member_details', member: member %>
          </li>
        <% end %>
      </ol>
    </section>
  </div>
</div>