config/routes.rb
Rails.application.routes.draw do

  root              'static_pages#home'

  get  'help',  to: 'static_pages#help'

  get  'about', to: 'static_pages#about'

  devise_for :users

  post 'print', defaults: { format: 'pdf' }, to: 'users#print'

  resources :pdf_templates

  resources :organizations do
    resources :members
    member { post 'print', defaults: { format: 'pdf' } }
  end

  resources :members, only: [:index]

  resources :groups do
    resources :members, only: [:index], controller: 'groups/members' do
      member do
        get 'add'
        get 'remove'
      end
    end
    resources :events do
      member { post 'print', defaults: { format: 'pdf' } }
    end
    member { post 'print', defaults: { format: 'pdf' } }
  end

  resources :events do
    resources :registrations, 
              only: [:index, :destroy], 
              controller: 'events/registrations' do
      member { get 'confirm' } 
    end

    member { get 'register', to: 'events/registrations#register' }
  end

  get "angular_test", to: "angular_test#index"

end

app/models/pdf_template.rb
class PdfTemplate < ActiveRecord::Base
  has_many :header_columns, dependent: :destroy
  has_one  :header, dependent: :destroy
  has_one  :footer, dependent: :destroy

  accepts_nested_attributes_for :header_columns, allow_destroy: true
  accepts_nested_attributes_for :header, allow_destroy: true
  accepts_nested_attributes_for :footer, allow_destroy: true

  validates :title, presence: true
  validates :associated_class, presence: true
  validates :column_class, presence: true
 end

app/models/pdf_template/printer.rb
module PdfTemplate::Printer

  PAGE_NUMBERING = ["<page>", "Page <page>", 
                    "<page>/<total>", "Page <page> of <total>"]
  DATE_FORMATS   = ["%d.%m.%Y - %H:%M:%S", "%d.%m - %H:%M", "%d.%m.%Y"]

  def to_pdf(template)
    pdf_template = PdfTemplate.find(template.to_i)

    orientation = if pdf_template.orientation.nil? 
                    :portrait 
                  else
                    pdf_template.orientation.to_sym
                  end

    pdf = Prawn::Document.new(page_size: "A4", page_layout: orientation)

    row_class = pdf_template.column_class.demodulize.downcase.pluralize
    header = pdf_template.header
    footer = pdf_template.footer
    values, headers, sizes = pdf_template.header_columns.map do |c| 
      [c.content, c.title, (c.size.nil? || c.size.empty?) ? 5 : c.size.to_i]
    end.transpose

    row_number = 0

    row_data = send(row_class).map do |klass|
      values.map do |v|
        if v.nil? || v.empty?
          ""
        elsif v == "#"
          sprintf("%d", (row_number += 1))
        else
          initial, *messages = v.split('.')
          messages.inject(klass.send(initial)) { |c, m| c.send(m) }.to_s
        end
      end if values
    end

    # header
    if header
      page_section(pdf, header.left, pdf.bounds.top_left, :left)
      page_section(pdf, header.middle, pdf.bounds.top_left, :center)
      page_section(pdf, header.right, pdf.bounds.top_left, :right)
    end

    # content
    pdf.move_down 15


    if row_data.empty?
      pdf.move_down 15
      pdf.text "No data available!"
    else
      pdf.table([headers, *row_data], cell_style: { size: 8, padding: 2 }, 
               column_widths: calculate_width(pdf, row_data, sizes)) do |t| 
        t.header = true
        t.columns(headers.index("#")).align = :right if headers.index("#")
        t.row(0).style(background_color: '44844', text_color: 'fffffff')
        t.row(0).font_style = :bold
        t.row(0).columns(0..headers.length).align = :center
      end
    end

    # footer
    if footer
      page_section(pdf, footer.left, [pdf.bounds.left, 12], :left)
      page_section(pdf, footer.middle, [pdf.bounds.left, 12], :center)
      page_section(pdf, footer.right, [pdf.bounds.left, 12], :right)
    end

    pdf.render
  end

  private

    def page_section(pdf, content, position, horizontal)
      options = {
        at: position,
        width: pdf.bounds.width,
        align: horizontal,
        single_line: true,
        size: 10
      }

      if PAGE_NUMBERING.include? content
        pdf.number_pages(content, options) 
      else
        value = if DATE_FORMATS.include? content
                  Time.now.strftime(content)
                else
                  if content.nil?
                    "no data"
                  else 
                    content.empty? ? "" : send(content).to_s
                  end
                end
        pdf.repeat(:all) { pdf.text_box(value, options) }
      end
    end

    def calculate_width(pdf, values, sizes)
      column_sizes = [values.transpose.map do |c| 
                       c.inject { |m, v| m > v ? m : v }.length
                     end,
                     sizes].transpose.map { |v| v.max }

      pdf_width = pdf.bounds.width
      column_sizes_sum = column_sizes.sum
      column_sizes.map { |value| value * pdf_width / column_sizes_sum }
    end

    def get_value(value)
       
    end
end

app/controllers/pdf_templates_controller.rb
class PdfTemplatesController < ApplicationController

  def index
    load_templates
  end

  def new
    build_template
    load_classes
  end

  def edit
    load_template
    load_attributes
  end

  def create
    build_template
    save_template or render_new
  end

  def update
    load_template
    build_template
    save_template or render_edit
  end

  def destroy
    load_template
    @template.destroy
    redirect_to pdf_templates_path
  end

  private

    def load_templates
      @templates ||= templates
    end

    def load_template
      @template ||= templates.find(params[:id])
    end

    def build_template
      @template ||= build_new_template
      @template.attributes = template_params
    end

    def save_template
      if @template.save
        redirect_to pdf_templates_path
      end
    end

    def build_new_template
      template = templates.build
      template.build_header
      template.header_columns.build
      template.build_footer
      template
    end

    def templates
      PdfTemplate.all
    end

    def template_params
      template_params = params[:pdf_template]
      template_params ? template_params.permit(
                               :title, :associated_class, :column_class,
                               :orientation,
                                       header_attributes: [:id, :left,
                                                           :middle, :right,
                                                           :pdf_template_id],
                               header_columns_attributes: [:id, 
                                                           :content,
                                                           :title,
                                                           :size,
                                                           :pdf_template_id,
                                                           :_destroy], 
                                       footer_attributes: [:id, :left,
                                                           :middle, :right,
                                                           :pdf_template_id]
                               ) : {}
    end

    def render_new
      load_classes
      render :new
    end

    def render_edit
      load_attributes
      render :edit
    end

    def load_classes
      classes = [User, Event, Organization, Group, Member]
      @associated_classes = classes.map(&:name)
      @column_classes = grouped_classes(classes)
    end

    def grouped_classes(classes)
      grouped_classes = {}
      classes.each do |c|
#        grouped_classes[c] = c.reflect_on_all_associations(:has_many)
#                              .map(&:klass).map(&:name)
        grouped_classes[c] = reflection_attributes(c, 
                             [:has_many, :has_and_belongs_to_many]).map(&:name)
      end
      grouped_classes
    end

    def load_attributes
      @associated_class_attributes = @template.associated_class
                                                  .classify
                                                  .constantize
                                                  .attribute_names
      @column_class_attributes = grouped_attributes(@template.column_class
                                                                 .classify
                                                                 .constantize)
    end

    def grouped_attributes(klass)
      has_one = if reflection_attributes(klass, [:has_one]).empty?
                  {}
                else
                  attributes(klass, :has_one)
                end
      belongs_to = if reflection_attributes(klass, [:belongs_to]).empty?
                     {}
                   else
                     attributes(klass, :belongs_to)
                   end
      { klass.name.underscore => klass.attribute_names }.merge(has_one)
                                                        .merge(belongs_to)
    end

    def attributes(klass, macro, hash={}, ancestors="")
      klass.reflect_on_all_associations(macro).map(&:klass).each do |k|
        ancestor = ancestor_path(ancestors, k)
        hash[ancestor] = class_attribute_names(ancestor, k)
        attributes(k, macro, hash, ancestor_path(ancestors, k))
      end
      hash
    end

    def class_attribute_names(ancestors, klass)
      klass.attribute_names.map do |a| 
        [a, "#{ancestors}.#{a}"]
      end
    end

    def ancestor_path(ancestors, klass)
      if ancestors.empty?
        klass.name.underscore
      else
        "#{ancestors}.#{klass.name.underscore}"
      end
    end

    def reflection_attributes(klass, macros)
      macros.map do |m|
        klass.reflect_on_all_associations(m).map(&:klass)
      end.flatten
    end
end

app/helpers/pdf_templates_helper.rb
module PdfTemplatesHelper
  def templates(klass)
    PdfTemplate.all.where('associated_class = ?', klass)
                   .collect { |t| ["#{t.title} (#{t.orientation})", t.id] }
  end
end

app/views/pdf_templates/_form.html.erb
<%= render partial: 'shared/generic_error_message',
  locals: { topic: @template } %>

<%= form_for @template do |f| %>
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, autofocus: true, class: "form-control" %>
      </div>
    </div>

    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :orientation %>
        <%= f.select :orientation, 
          options_for_select(["portrait", "landscape"], f.object.orientation), 
          {}, { class: "form-control" } %>
      </div>
    </div>
  </div>


  <h2>Header <small><%= @template.associated_class %></small></h2>
  <%= f.fields_for :header, @template.header do |g| %>
    <%= render 'static_fields', g: g %>
  <% end %>

  <h2>Columns <small><%= @template.column_class.capitalize %></small></h2>
  <%= f.fields_for :header_columns do |g| %>
    <%= render 'header_column_fields', g: g %>
  <% end %>
  <p><%= link_to_add_fields 'Add column', f, :header_columns %></p>

  <h2>Footer <small><%= @template.associated_class %></small></h2>
  <%= f.fields_for :footer, @template.footer do |g| %>
    <%= render 'static_fields', g: g %>
  <% end %>

  <%= f.submit class: "btn btn-primary" %> | <%= link_to "Cancel", :back %>
<% end %>

app/views/pdf_templates/_global_printer.html.erb
<% options = templates(klass) %>
<% unless options.empty? %>
  <div class="form-group pull-right">
    <%= form_tag(path, class: "form-inline") do %>
      <%= select_tag :template, options_for_select(options),
        { class: "form-control" } %>
      <%= submit_tag 'Print', class: "btn btn-default" %>
    <% end %>
  </div>
<% end %>

app/views/pdf_templates/_header_column_fields.html.erb
<div class="row">
  <div class="col-md-3">
    <div class="form-group">
      <%= g.label :content %>
      <%= g.select :content, 
       grouped_options_for_select(@column_class_attributes.merge({row: ["#"]}),
                                  g.object.content),
                   { include_blank: '' }, 
                   { class: "column-header form-control" } %>
    </div>
  </div>

  <div class="col-md-3">
    <div class="form-group">
      <%= g.label :title %>
      <%= g.text_field :title, { class: "column-name form-control" } %>
    </div>
  </div>

  <div class="col-md-3">
    <div class="form-group">
      <%= g.label :size %>
      <%= g.text_field :size, { class: "form-control" } %>
    </div>
  </div>

  <div class="col-md-3">
    <%= g.hidden_field :_destroy %>
    <%= link_to "Remove", '#', class: "remove_fields btn btn-warning" %>
  </div>
  </br>
</div>

app/views/pdf_templates/_printer.html.erb
<% options = templates(klass) %>
<% unless options.empty? %>
  <h2 class="pull-left">
    <div class="form-group">
      <%= form_tag(path, class: "form-inline") do %>
        <%= select_tag :template, options_for_select(options),
          { class: "form-control input-sm" } %>
        <%= submit_tag 'Print', class: "btn btn-default btn-sm" %>
      <% end %>
    </div>
  </h2>
<% end %>

app/views/pdf_templates/_static_fields.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="form-group">
      <%= g.label :left %>
      <%= g.select :left, options_for_select(@associated_class_attributes + 
                          PdfTemplate::Printer::PAGE_NUMBERING +
                          PdfTemplate::Printer::DATE_FORMATS, g.object.left),
                   { include_blank: true }, { class: "form-control" } %>
  </div>

  </div><div class="col-md-4">
    <div class="form-group">
      <%= g.label :middle %>
      <%= g.select :middle, options_for_select(@associated_class_attributes + 
                           PdfTemplate::Printer::PAGE_NUMBERING +
                           PdfTemplate::Printer::DATE_FORMATS, g.object.middle),
                   { include_blank: true }, { class: "form-control" } %>
  </div>

  </div><div class="col-md-4">
    <div class="form-group">
      <%= g.label :right %>
      <%= g.select :right, options_for_select(@associated_class_attributes + 
                           PdfTemplate::Printer::PAGE_NUMBERING +
                           PdfTemplate::Printer::DATE_FORMATS, g.object.right),
                   { include_blank: true }, { class: "form-control" } %>
    </div>
  </div>
</div>

app/views/pdf_templates/edit.html.erb
<%= provide(:title, 'Edit Template') %>

<%= render 'form' %>

app/views/pdf_templates/index.html.erb
<% provide(:title, "Templates") %>

<section class="results">
  <header>
    <h1 class="h3">Templates</h1>
  </header>
  
  <section class="link-area">
    </br>
    <%= link_to "Create new template", new_pdf_template_path, 
      class: "btn btn-primary" %></br></br>
  </section>

  <ol class="list-group">
    <% @templates.each do |template| %>
      <li class="list-group-item clearfix">
        <h2 class="pull-right">
          <%= link_to "Edit", 
            edit_pdf_template_path(template), 
            class: "btn btn-primary btn-sm" %> 
          <%= link_to "Delete", 
            [template], 
            method: :delete, 
            data: { confirm: "You are about to delete the template. 
                    Do you want to delete now?" }, 
            class: "btn btn-warning btn-sm" %>
        </h2>

        <h2 class="h3">
          <i class="glyphicon glyphicon-th-list"></i>
          <%= template.title %> <%= template.associated_class %> 
          <%= template.orientation %></br>
          <small><%= template.updated_at %></small>
        </h2>

        <div class="panel panel-default">
          <div class="panel-heading">
            <div class="panel-title">
              <%= template.title %>
            </div>
          </div>
          <table class="table table-small">
            <tr>
              <th><%= template.header.left   %></td>
              <th><%= template.header.middle %></td>
              <th><%= template.header.right  %></td>
            </tr>
            <% template.header_columns.each do |column| %>
              <tr>
                <td><%= column.content %></td>
                <td><%= column.title %></td>
                <td><%= column.size %></td>
              </tr>
            <% end %>
            <tr>
              <th><%= template.footer.left   %></td>
              <th><%= template.footer.middle %></td>
              <th><%= template.footer.right  %></td>
            </tr>
          </table>
        </div>
      </li>
    <% end %>
  </ol>
</section>

app/views/pdf_templates/new.html.erb
<%= provide(:title, 'Create new Template') %>

<%= render partial: 'shared/generic_error_message',
  locals: { topic: @template } %>

<%= form_for @template do |f| %>
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, autofocus: true, class: "form-control" %>
      </div>
    </div>

    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :associated_class %>
        <%= f.select :associated_class, 
          options_for_select(@associated_classes), 
          { include_blank: '' }, { class: "form-control associated-class" } %>
      </div>
    </div>

    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :column_class %>
        <%= f.select :column_class, 
          grouped_options_for_select(@column_classes), 
          { include_blank: '' }, { class: "form-control column-class" } %>
      </div>
    </div>
  </div>

  <%= f.submit class: "btn btn-primary" %> | <%= link_to "Cancel", :back %>
<% end %>