config/routes.rb
Rails.application.routes.draw do

  root              'static_pages#home'

  get  'help',  to: 'static_pages#help'

  get  'about', to: 'static_pages#about'

  devise_for :users

  post 'print', defaults: { format: 'pdf' }, to: 'users#print'

  resources :pdf_templates

  resources :organizations do
    resources :members
    member { post 'print', defaults: { format: 'pdf' } }
  end

  resources :members, only: [:index]

  resources :groups do
    resources :members, only: [:index], controller: 'groups/members' do
      member do
        get 'add'
        get 'remove'
      end
    end
    resources :events do
      member { post 'print', defaults: { format: 'pdf' } }
    end
    member { post 'print', defaults: { format: 'pdf' } }
  end

  resources :events do
    resources :registrations, 
              only: [:index, :destroy], 
              controller: 'events/registrations' do
      member { get 'confirm' } 
    end

    member { get 'register', to: 'events/registrations#register' }
  end

  get "angular_test", to: "angular_test#index"

end

app/views/layouts/_footer.html.erb
<footer class="navbar navbar-inverse navbar-fixed-bottom">
  <div class="container">
    <button type="button" class="navbar-toggle collapsed"
      data-toggle="collapse" data-target="#collapsable-footer"
      aria-expanded="false">
      <span class="sr-only">Toggle footer navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

    <div class="collapse navbar-collapse" id="collapsable-footer">
      <ul class="nav navbar-nav">
        <li>
          <a href="https://github.com/sugaryourcoffee/circlus", target="_blank">
            Circlus <%= Rails.configuration.version %> by Sugar Your Coffee
          </a> 
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Terms of Use', "#" %></li>
        <li><%= link_to 'About Us', about_path %></li>
        <li><%= link_to 'Contact', "#" %></li>
      </ul>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <nav>
      <button type="button" class="navbar-toggle collapsed"
        data-toggle="collapse" data-target="#collapsable-navbar"
        aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to "Circlus", root_path, class: "navbar-brand" %>

      <div class="collapse navbar-collapse" id="collapsable-navbar">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'Help', help_path %></li>
          <li><%= link_to 'Organizations', organizations_path %></li>
          <li><%= link_to 'Members', members_path %></li>
          <li><%= link_to 'Groups', groups_path %></li>
          <li><%= link_to 'Events', events_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              New<b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'New Organization', new_organization_path %></li>
              <li><%= link_to 'New Group', new_group_path %></li>
              <li><%= link_to 'Templates', pdf_templates_path %></li>
            </ul>
          </li>
          <% if current_user %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account<b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to 'My Contacts', organizations_path %></li>
                <li><%= link_to 'Settings', edit_user_registration_path %></li>
                <li><%= link_to 'Sign out', destroy_user_session_path,
                        method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'Sign in', new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="mobile-web-app-capable" content="yes">
    <title><%= yield :title %> | Circlus</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% if notice.present? %>
        <aside class="alert alert-info">
          <%= notice %>
        </aside>
      <% end %>
      <% if alert.present? %>
        <aside class="alert alert-danger">
          <%= alert %>
        </aside>
      <% end %>

      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>

    <%= debug(params) if Rails.env.development? %>

  </body>
</html>